apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-flask-app
  labels:
    app: ai-flask-app
  namespace: python
spec:
  # A contagem de réplicas foi removida.
  # O KEDA agora tem controle total sobre o escalonamento.
  selector:
    matchLabels:
      app: ai-flask-app
  template:
    metadata:
      labels:
        app: ai-flask-app
    spec:
      containers:
      - name: ai-flask-app
        image: 490498244836.dkr.ecr.us-east-1.amazonaws.com/app-python:latest
        ports:
        - containerPort: 8080
        env:
        - name: IMAGE_VERSION
          value: "latest"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
