apiVersion: v1
kind: Service
metadata:
  name: ai-flask-app-service
  namespace: python
spec:
  # Usando LoadBalancer para expor o serviço externamente (em um provedor de nuvem real)
  # Para Minikube, você usaria `minikube service ai-flask-app-service` para acessar.
  type: LoadBalancer 
  selector:
    app: ai-flask-app
  ports:
    - protocol: TCP
      port: 80 # Porta externa
      targetPort: 8080 # Porta do container