name: CD - Terraform Destroy

on: workflow_dispatch

env:
  AWS_REGION: us-east-1

jobs:
  delete_infra_aws:
    name: terraform
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v2

      - name: 2. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 3. Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: 4. Terraform Init
        id: init
        run: terraform init -input=false -upgrade -reconfigure
        working-directory: terraform

      - name: 5. Terraform Apply
        id: apply
        run: terraform apply -destroy -input=false -auto-approve
        working-directory: terraform
