name: CD - Deploy no Kubernetes

on:
  workflow_run:
    workflows: ["CD - Terraform"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy no Ambiente de Produção
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: "us-east-1"
      CLUSTER_NAME: "fiap-eks"

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      - name: 2. AI Code Review
        if: github.event_name == 'pull_request'
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CONFIG.MODEL: "gemini/gemini-1.5-flash-latest"

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Instalar dependências do script de IA
        run: pip install requests

      - name: 5. Baixar e Executar Script Gerador de Dockerfile
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Baixando script de IA..."
          curl -sSL ${{ secrets.GEMINI_GERADOR_DOCKERFILE_URL }} -o generate_dockerfile.py
          echo "Executando script..."
          python generate_dockerfile.py

      - name: 4. Commitar o Dockerfile gerado (se estiver na branch main)
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: ✨ Gera e commita Dockerfile via IA"
          file_pattern: Dockerfile

      - name: 5. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: 6. Login ECR
        run: |
          aws ecr get-login-password \
          --region ${{ env.AWS_REGION }} | \
          docker login --username AWS \
          --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: 7. BuildAndPush Dockerfile
        run: |
          docker build -t app-python . && \
          docker tag app-python:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/app-python:latest && \
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/app-python:latest

      - name: 8. Update Kube Config
        run: |
          aws eks update-kubeconfig \
          --name ${{ env.CLUSTER_NAME }} \
          --region ${{ env.AWS_REGION }}

      - name: 9. Aplicar Configurações de Escalabilidade (Karpenter e KEDA)
        run: |
          echo "--- Aplicando configurações do Karpenter e KEDA ---"
          kubectl apply -f k8s/ns.yaml && \
          kubectl apply -f k8s-addons/karpenter/
          kubectl apply -f k8s-addons/keda/
          echo "---------------------------------------------------"

      - name: 10. Realizar o Deploy da Aplicação
        run: |
          echo "--- Aplicando manifestos da aplicação ---"
          cat k8s/deployment.yaml
          cat k8s/service.yaml
          echo "-----------------------------------------"
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          echo "🚀 Deploy da aplicação iniciado!"

      - name: 11. Verificar o status do deploy
        run: |
          echo "Aguardando o deploy ficar pronto..."
          kubectl rollout status deployment/ai-flask-app -n default --timeout=120s
