name: CI - Terraform

on:
  pull_request:

env:
  AWS_REGION: us-east-1

jobs:
  ci:
    name: Continuos Integration
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repo
        uses: actions/checkout@v4

      - name: 2. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 3. Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: 4. Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: terraform

      - name: 5. Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: terraform

      - name: 6. Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color -input=false
        working-directory: terraform
        continue-on-error: true